### ISSUE TITLE
support letter case

### ISSUE THREAD

**Issue by foray1010** [PaulRosset/linter-farch#2]
creating regex for letter case checking is troublesome, I suggest we can have some preset enums

for example, I would like to force using lower camel case and upper camel case in whole project

```json
{
  "farch": {
    "src": ["LOWER_CAMEL_CASE", "UPPER_CAMEL_CASE"]
  }
}
```

**Comment by PaulRosset** [comment]
@foray1010 Hi, Thank's you for the feedback!!

Yes, I realized that writting regex is something that have to be the most possible avoided, but I would like to keep it of course possible.

**Comment by foray1010** [comment]
just cleaning up my inactive issues
